services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # để Jenkins container có thể dùng Docker CLI của host
    user: root # để Jenkins có quyền chạy Docker CLI

volumes:
  jenkins_home: